# Generated by Django 4.0.4 on 2022-05-29 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_ovc', '0002_alter_ovchhmembers_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_registry', '0002_alter_ovchousehold_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCPMTCTRegistration',
            fields=[
                ('pmtct_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('caregiver_contact', models.CharField(max_length=15)),
                ('hiv_status', models.CharField(max_length=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exit_reason', models.CharField(max_length=4, null=True)),
                ('exit_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('sync_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('caregiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pmtct_caregiver', to='cpovc_registry.regperson')),
                ('child_cbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmtct_cbo', to='cpovc_registry.regorgunit')),
                ('chv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pmtct_chv', to='cpovc_registry.regperson')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovcschool')),
            ],
            options={
                'db_table': 'ovc_pmtct_registration',
            },
        ),
    ]
