# Generated by Django 4.0.2 on 2022-03-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_order', models.IntegerField(default=1)),
                ('faq_title', models.CharField(max_length=255)),
                ('faq_details', models.TextField()),
                ('faq_timestamp', models.DateTimeField()),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'FAQ Detail',
                'verbose_name_plural': 'FAQ Details',
                'db_table': 'ovc_faq',
            },
        ),
        migrations.CreateModel(
            name='OVCDownloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('version', models.DecimalField(decimal_places=2, max_digits=5)),
                ('doc_date', models.DateField()),
                ('doc_details', models.TextField()),
                ('downloads', models.BigIntegerField(default=0)),
                ('doc_tags', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents')),
                ('is_public', models.BooleanField(default=False)),
                ('is_void', models.BooleanField(default=False)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'verbose_name': 'DCS / OVC Document',
                'verbose_name_plural': 'DCS / OVC Documents',
                'db_table': 'ovc_downloads',
            },
        ),
    ]
