# Generated by Django 4.0.2 on 2022-04-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovcdownloads',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
    ]
