# Generated by Django 4.0.2 on 2022-05-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setuplist',
            name='item_id',
            field=models.CharField(max_length=10),
        ),
    ]
