# Generated by Django 4.0.2 on 2022-05-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_main', '0002_alter_setuplist_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setuplist',
            name='timestamp_updated',
        ),
    ]
