# Generated by Django 4.0.4 on 2022-05-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setuplist',
            name='item_description_short',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
