# Generated by Django 4.0.2 on 2022-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setuplist',
            name='item_category',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='setuplist',
            name='item_description',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='setuplist',
            name='item_description_short',
            field=models.CharField(max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name='setuplist',
            name='item_sub_category',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
    ]
