# Generated by Django 4.0.2 on 2022-05-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_main', '0003_alter_setuplist_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setuplist',
            name='field_name',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='setuplist',
            name='item_id',
            field=models.CharField(max_length=47),
        ),
    ]
