# Generated by Django 4.0.4 on 2022-05-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_main', '0004_alter_setuplist_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setuplist',
            name='item_description_short',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
