# Generated by Django 4.0.2 on 2022-05-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_main', '0005_alter_setuplist_item_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setuplist',
            name='item_description_short',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='setuplist',
            name='item_id',
            field=models.CharField(max_length=100),
        ),
    ]
