# Generated by Django 4.0.2 on 2022-04-26 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '__first__'),
        ('cpovc_ovc', '__first__'),
        ('cpovc_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 9, 29, 14, 349182)),
        ),
        migrations.CreateModel(
            name='OVCBenchmarkMonitoring',
            fields=[
                ('bench_mark_monitoring_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bench_mark1', models.CharField(blank=True, max_length=10, null=True)),
                ('bench_mark2', models.CharField(blank=True, max_length=10, null=True)),
                ('bench_mark3', models.CharField(blank=True, max_length=10, null=True)),
                ('bench_mark4', models.CharField(blank=True, max_length=10, null=True)),
                ('bench_mark5', models.CharField(blank=True, max_length=10, null=True)),
                ('bench_mark6', models.CharField(blank=True, max_length=10, null=True)),
                ('bench_mark7', models.CharField(blank=True, max_length=10, null=True)),
                ('bench_mark8', models.CharField(blank=True, max_length=10, null=True)),
                ('bench_mark9', models.CharField(blank=True, max_length=10, null=True)),
                ('monitoring_date', models.IntegerField(default=0)),
                ('is_void', models.BooleanField(default=False)),
                ('date_of_event', models.DateField(default=django.utils.timezone.now)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('care_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovchousehold')),
            ],
            options={
                'db_table': 'ovc__benchmark_monitoring',
            },
        ),
    ]
