# Generated by Django 4.0.2 on 2022-05-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OVCCareCaseExit',
        ),
    ]
