# Generated by Django 4.0.2 on 2022-04-29 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_ovc', '__first__'),
        ('cpovc_registry', '__first__'),
        ('cpovc_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCBenchmarkMonitoring',
            fields=[
                ('obm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Benchmark1', models.BooleanField()),
                ('Benchmark2', models.BooleanField()),
                ('Benchmark3', models.BooleanField()),
                ('Benchmark4', models.BooleanField()),
                ('Benchmark6', models.BooleanField()),
                ('Benchmark7', models.BooleanField()),
                ('Benchmark8', models.BooleanField()),
                ('Benchmark9', models.BooleanField()),
                ('case_closure_checked', models.BooleanField()),
                ('succesful_exit_checked', models.BooleanField()),
                ('is_void', models.BooleanField(default=False)),
                ('event_date', models.DateField()),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovchousehold')),
            ],
            options={
                'db_table': 'ovc_benchmark_monitoring',
            },
        ),
        migrations.DeleteModel(
            name='OVCGradMonitorTool',
        ),
    ]
