# Generated by Django 4.0.2 on 2022-04-30 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '__first__'),
        ('cpovc_ovc', '__first__'),
        ('cpovc_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCCareCpara_upgrade',
            fields=[
                ('cpara_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_code', models.CharField(blank=True, max_length=10)),
                ('answer', models.CharField(max_length=15)),
                ('question_type', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('date_of_event', models.DateField()),
                ('date_of_previous_event', models.DateField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpara_caregiver_upgrade', to='cpovc_registry.regperson')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovchousehold')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccarequestions')),
            ],
            options={
                'db_table': 'ovc_care_cpara_upgrade',
            },
        ),
        migrations.CreateModel(
            name='OVCBenchmarkMonitoring',
            fields=[
                ('obm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Benchmark1', models.BooleanField()),
                ('Benchmark2', models.BooleanField()),
                ('Benchmark3', models.BooleanField()),
                ('Benchmark4', models.BooleanField()),
                ('Benchmark5', models.BooleanField()),
                ('Benchmark6', models.BooleanField()),
                ('Benchmark7', models.BooleanField()),
                ('Benchmark8', models.BooleanField()),
                ('Benchmark9', models.BooleanField()),
                ('case_closure_checked', models.BooleanField()),
                ('succesful_exit_checked', models.BooleanField()),
                ('is_void', models.BooleanField(default=False)),
                ('event_date', models.DateField()),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovchousehold')),
            ],
            options={
                'db_table': '`ovc_benchmark_monitoring`',
            },
        ),
    ]
