# Generated by Django 4.0.2 on 2022-04-30 16:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '__first__'),
        ('cpovc_ovc', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCPreventiveEvents',
            fields=[
                ('event', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('event_type_id', models.CharField(max_length=20)),
                ('event_counter', models.IntegerField(default=0)),
                ('event_score', models.IntegerField(default=0, null=True)),
                ('date_of_event', models.DateField(default=django.utils.timezone.now)),
                ('date_of_previous_event', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(default=404, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('sync_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('app_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('house_hold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovchousehold')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'db_table': 'ovc_preventive_events',
            },
        ),
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 19, 55, 46, 473024)),
        ),
        migrations.CreateModel(
            name='OVCPrevSinovyoCaregiverEvaluation',
            fields=[
                ('evaluation_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('type_of_assessment', models.CharField(max_length=40)),
                ('date_of_assessment', models.DateTimeField()),
                ('bd_age', models.CharField(max_length=40)),
                ('bd_sex', models.CharField(max_length=40)),
                ('bd_read', models.CharField(max_length=40)),
                ('bd_education_level', models.CharField(max_length=40)),
                ('bd_biological_children', models.CharField(max_length=40)),
                ('bd_non_biological_children', models.CharField(max_length=40)),
                ('bd_children_not_in_school', models.CharField(max_length=40)),
                ('watch_tv_with_child', models.CharField(max_length=40)),
                ('bd_source_income', models.CharField(max_length=40)),
                ('bd_adults_contribute_hh_income', models.CharField(max_length=40)),
                ('bd_children_contribute_hh_income', models.CharField(max_length=40)),
                ('bd_biological_mother', models.CharField(max_length=40)),
                ('bd_bm_live_hh', models.CharField(max_length=40, null=True)),
                ('bd_biological_father', models.CharField(max_length=40)),
                ('bd_bf_live_hh', models.CharField(max_length=40, null=True)),
                ('bd_money_basic_expenses', models.CharField(max_length=40)),
                ('bd_violence', models.CharField(max_length=40)),
                ('bd_adult_unwell', models.CharField(max_length=40)),
                ('bad_things_from_sex', models.CharField(max_length=40)),
                ('bd_child_unwell', models.CharField(max_length=40)),
                ('bd_miss_school', models.CharField(max_length=40)),
                ('bd_hiv_status', models.CharField(max_length=40)),
                ('bd_children_hiv_status', models.CharField(max_length=40)),
                ('bd_hiv_prevention', models.CharField(max_length=40)),
                ('bd_two_meals', models.CharField(max_length=40)),
                ('bd_missing_meal', models.CharField(max_length=40)),
                ('rc_discuss_child_needs', models.CharField(max_length=40)),
                ('rc_discipline', models.CharField(max_length=40)),
                ('rc_tells_bothering', models.CharField(max_length=40)),
                ('rc_involve_decisions', models.CharField(max_length=40)),
                ('cb_child_obedient', models.CharField(max_length=40)),
                ('cb_figths_children', models.CharField(max_length=40)),
                ('dc_often_discipline', models.CharField(max_length=40)),
                ('dc_physical_discipline', models.CharField(max_length=40)),
                ('dc_upstet_child', models.CharField(max_length=40)),
                ('sp_caring_energy', models.CharField(max_length=40)),
                ('sp_source_stress', models.CharField(max_length=40)),
                ('sp_physical_punish', models.CharField(max_length=40)),
                ('fs_depressed', models.CharField(max_length=80)),
                ('fs_effort', models.CharField(max_length=80)),
                ('fs_hopeful', models.CharField(max_length=80)),
                ('fi_money_important_items', models.CharField(max_length=40)),
                ('fi_worried_money', models.CharField(max_length=40)),
                ('fmp_pre_grouping_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('sync_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('event', models.ForeignKey(default='15657fa6-c860-11ec-b9d4-00e18c9fac49', on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovcpreventiveevents')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('ref_caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preval_caregiver', to='cpovc_registry.regperson')),
            ],
            options={
                'db_table': 'ovc_prev_sinovuyo_caregiver_evaluation',
            },
        ),
    ]
