# Generated by Django 4.0.2 on 2022-05-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovcbenchmarkmonitoring',
            name='succesful_exit_checked',
            field=models.BooleanField(),
        ),
    ]
