# Generated by Django 4.0.2 on 2022-04-28 09:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_forms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCFMPEvaluation',
            fields=[
                ('evaluation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_type', models.CharField(max_length=20, null=True)),
                ('caregiver_know_where', models.CharField(max_length=50, null=True)),
                ('caregiver_know_what', models.CharField(max_length=50, null=True)),
                ('caregiver_know_who', models.CharField(max_length=50, null=True)),
                ('child_watch_often', models.CharField(max_length=50, null=True)),
                ('what_program', models.CharField(max_length=50, null=True)),
                ('specific_program', models.CharField(max_length=50, null=True)),
                ('talk_on_topic', models.CharField(max_length=50, null=True)),
                ('watch_with_child', models.CharField(max_length=50, null=True)),
                ('talk_on_sex', models.CharField(max_length=50, null=True)),
                ('talk_on_hiv', models.CharField(max_length=50, null=True)),
                ('talk_on_sti', models.CharField(max_length=50, null=True)),
                ('other_sexual_issues', models.CharField(max_length=50, null=True)),
                ('if_yes', models.CharField(max_length=50, null=True)),
                ('child_asks', models.CharField(max_length=50, null=True)),
                ('if_asks', models.CharField(max_length=50, null=True)),
                ('comfortable', models.CharField(max_length=50, null=True)),
                ('how_talk', models.CharField(max_length=50, null=True)),
                ('enough_information', models.CharField(max_length=50, null=True)),
                ('talk_bad_things', models.CharField(max_length=50, null=True)),
                ('ask_questions', models.CharField(max_length=50, null=True)),
                ('thoughts_on_sex', models.CharField(max_length=50, null=True)),
                ('ready_to_learn', models.CharField(max_length=50, null=True)),
                ('still_young', models.CharField(max_length=50, null=True)),
                ('have_someone', models.CharField(max_length=50, null=True)),
                ('guardian_responsibility', models.CharField(max_length=50, null=True)),
                ('happy_with_child', models.CharField(max_length=50, null=True)),
                ('date_of_event', models.DateField(default=django.utils.timezone.now, null=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'db_table': 'ovc_fmp_evaluation',
            },
        ),
    ]
