# Generated by Django 4.0.2 on 2022-05-03 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0002_alter_ovcsibling_id_alter_regbiometric_id_and_more'),
        ('cpovc_forms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCBiReferral',
            fields=[
                ('refferal_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('client_category', models.CharField(default='OVC', max_length=20)),
                ('refferal_urgency', models.CharField(default='Urgent', max_length=10)),
                ('refferal_to', models.CharField(default='healthit', max_length=10)),
                ('refferal_status', models.CharField(default='PENDING', max_length=20)),
                ('refferal_date', models.DateField()),
                ('refferal_enddate', models.DateField()),
                ('refferal_service', models.CharField(max_length=100)),
                ('referral_grouping_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('sync_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('person', models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('ref_caregiver', models.ForeignKey(default=59, on_delete=django.db.models.deletion.CASCADE, related_name='refferal_caregiver', to='cpovc_registry.regperson')),
            ],
            options={
                'db_table': 'ovc_bi_referrals',
            },
        ),
    ]
