# Generated by Django 4.0.4 on 2022-05-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0002_rename_bench_mark_1_ovccarebenchmarkscore_benchmark_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovccareforms',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
