# Generated by Django 4.0.2 on 2022-04-30 07:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_forms', '0003_sinovuyuteenpreandpostassesment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovcprevsinovyoteenevaluation',
            name='ref_caregiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preval_caregiver', to='cpovc_registry.regperson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 10, 54, 7, 644481)),
        ),
    ]
