# Generated by Django 4.0.4 on 2022-07-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0003_pmtctevents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmtctevents',
            name='app_user',
        ),
        migrations.RemoveField(
            model_name='pmtctevents',
            name='person',
        ),
        migrations.RemoveField(
            model_name='pmtcthei',
            name='caregiver',
        ),
        migrations.RemoveField(
            model_name='pmtcthei',
            name='event',
        ),
        migrations.RemoveField(
            model_name='pmtcthei',
            name='person',
        ),
        migrations.RemoveField(
            model_name='pmtcthei',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pmtctquestions',
            name='form',
        ),
        migrations.AddField(
            model_name='ovchivmanagement',
            name='attendingsuppportgroup',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ovchivmanagement',
            name='currentregimen',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ovchivmanagement',
            name='enoughdrugs',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ovchivmanagement',
            name='enrolledotz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ovchivmanagement',
            name='pamacare',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ovchivmanagement',
            name='weight',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ovccarecpara',
            name='date_of_event',
            field=models.DateField(default=''),
        ),
        migrations.AlterModelTable(
            name='ovcbenchmarkmonitoring',
            table='ovc_benchmark_monitoring',
        ),
        migrations.DeleteModel(
            name='OVCHEITracker',
        ),
        migrations.DeleteModel(
            name='PMTCTEvents',
        ),
        migrations.DeleteModel(
            name='PMTCTHEI',
        ),
        migrations.DeleteModel(
            name='PMTCTQuestions',
        ),
    ]
