# Generated by Django 4.0.2 on 2022-05-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0003_ovccarecaseexit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OVCCareCaseExit',
        ),
    ]
