# Generated by Django 4.0.2 on 2022-04-29 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0003_ovcpreventiveevents_alter_listbanks_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 22, 56, 34, 231942)),
        ),
    ]
