# Generated by Django 4.0.2 on 2022-04-30 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_ovc', '0001_initial'),
        ('cpovc_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_forms', '0003_ovcfmpevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCPreventiveEvents',
            fields=[
                ('event', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('event_type_id', models.CharField(max_length=10)),
                ('event_counter', models.IntegerField(default=0)),
                ('event_score', models.IntegerField(default=0, null=True)),
                ('date_of_event', models.DateField(default=django.utils.timezone.now)),
                ('date_of_previous_event', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(default=404, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('sync_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('app_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('house_hold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovchousehold')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'db_table': 'ovc_preventive_events',
            },
        ),
        migrations.CreateModel(
            name='OVCPrevEvaluation',
            fields=[
                ('evaluation_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('know_where', models.CharField(max_length=10)),
                ('know_what', models.CharField(max_length=10)),
                ('know_who', models.CharField(max_length=10)),
                ('often_watch_tv', models.CharField(max_length=10)),
                ('know_what_watching_tv', models.CharField(max_length=10)),
                ('not_watch_programs_tv', models.CharField(max_length=10)),
                ('talk_sex_on_tv', models.CharField(max_length=10)),
                ('watch_tv_with_child', models.CharField(max_length=10)),
                ('what_sex_is', models.CharField(max_length=10)),
                ('talk_hiv', models.CharField(max_length=10)),
                ('talk_sti', models.CharField(max_length=10)),
                ('talk_sex_issues', models.CharField(max_length=10)),
                ('talk_sex_issue_what', models.CharField(max_length=10)),
                ('ask_sex_issue', models.CharField(max_length=10)),
                ('ask_sex_issue_respond', models.CharField(max_length=10)),
                ('question_about_sex_issue', models.CharField(max_length=10)),
                ('know_how_talk_sex_issue', models.CharField(max_length=10)),
                ('information_sex_issues', models.CharField(max_length=10)),
                ('bad_things_from_sex', models.CharField(max_length=10)),
                ('talk_sex_child_opinion', models.CharField(max_length=10)),
                ('ready_learn_sex_issues', models.CharField(max_length=10)),
                ('encourage_have_sex', models.CharField(max_length=10)),
                ('young_learn_sex_issues', models.CharField(max_length=10)),
                ('someone_talk_sex_issues', models.CharField(max_length=10)),
                ('parent_responsibility_talk_sex', models.CharField(max_length=10)),
                ('happy_with_child', models.CharField(max_length=10)),
                ('fmp_pre_grouping_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('sync_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovcpreventiveevents')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'db_table': 'ovc_prev_fmp_evaluation',
            },
        ),
    ]
