# Generated by Django 4.0.2 on 2022-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0003_ovcbireferral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovcbireferral',
            name='client_category',
            field=models.CharField(default='OVC', max_length=100),
        ),
        migrations.AlterField(
            model_name='ovcbireferral',
            name='refferal_service',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='ovcbireferral',
            name='refferal_status',
            field=models.CharField(default='PENDING', max_length=200),
        ),
        migrations.AlterField(
            model_name='ovcbireferral',
            name='refferal_to',
            field=models.CharField(default='healthit', max_length=100),
        ),
        migrations.AlterField(
            model_name='ovcbireferral',
            name='refferal_urgency',
            field=models.CharField(default='Urgent', max_length=100),
        ),
    ]
