# Generated by Django 4.0.2 on 2022-05-02 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0003_alter_ovchivmanagement_substitution_firstline_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovcprevsinovyocaregiverevaluation',
            name='bad_things_from_sex',
        ),
        migrations.RemoveField(
            model_name='ovcprevsinovyocaregiverevaluation',
            name='watch_tv_with_child',
        ),
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 21, 52, 18, 858136)),
        ),
        migrations.AlterField(
            model_name='ovcprevsinovyocaregiverevaluation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovcpreventiveevents'),
        ),
    ]
