# Generated by Django 4.0.2 on 2022-05-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_forms', '0003_alter_ovcbenchmarkmonitoring_succesful_exit_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovcbenchmarkmonitoring',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver', to='cpovc_registry.regperson'),
        ),
        migrations.AlterField(
            model_name='ovcbenchmarkmonitoring',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='cpovc_registry.regperson'),
        ),
    ]
