# Generated by Django 4.0.4 on 2022-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0003_alter_ovccareforms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovccarequestions',
            name='code_x',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
