# Generated by Django 4.0.4 on 2022-05-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '__first__'),
        ('cpovc_forms', '0004_ovccarequestions_code_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovccarequestions',
            name='code_x',
        ),
        migrations.AddField(
            model_name='ovccarecpara_upgrade',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccarequestions'),
        ),
        migrations.AlterField(
            model_name='ovccarecpara_upgrade',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpara_caregiver', to='cpovc_registry.regperson'),
        ),
        migrations.AlterField(
            model_name='ovccarecpara_upgrade',
            name='domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ovccarecpara_upgrade',
            name='question_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ovccarequestions',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ovccarequestions',
            name='domain',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ovccarequestions',
            name='question',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='ovccarequestions',
            name='question_text',
            field=models.CharField(max_length=255, null=True),
        )
    ]
