# Generated by Django 4.0.2 on 2022-05-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0004_alter_ovcbireferral_client_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovcbireferral',
            name='refferal_service',
            field=models.CharField(max_length=2256),
        ),
    ]
