# Generated by Django 4.0.4 on 2022-07-25 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0004_remove_pmtctevents_app_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovchivriskscreening',
            name='adol_had_tb',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ovchivriskscreening',
            name='sharing_needles',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ovchivriskscreening',
            name='traditional_procedure',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ovchivriskscreening',
            name='art_referral_completed_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ovchivriskscreening',
            name='art_referral_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ovchivriskscreening',
            name='parent_consent_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ovchivriskscreening',
            name='referral_completed_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ovchivriskscreening',
            name='referral_made_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
