# Generated by Django 4.0.2 on 2022-05-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0004_alter_ovcbenchmarkmonitoring_caregiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovcbenchmarkmonitoring',
            name='person',
        ),
    ]
