# Generated by Django 4.0.2 on 2022-04-30 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0004_ovcprevsinovyoteenevaluation_ref_caregiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovcprevsinovyoteenevaluation',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovcpreventiveevents'),
        ),
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 11, 11, 31, 120557)),
        ),
    ]
