# Generated by Django 4.0.2 on 2022-05-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0002_alter_ovcsibling_id_alter_regbiometric_id_and_more'),
        ('cpovc_forms', '0005_alter_ovcbireferral_refferal_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovcbireferral',
            name='client_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ovcbireferral',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
        migrations.AlterField(
            model_name='ovcbireferral',
            name='ref_caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferal_caregiver', to='cpovc_registry.regperson'),
        ),
        migrations.AlterField(
            model_name='ovcbireferral',
            name='refferal_to',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ovcbireferral',
            name='refferal_urgency',
            field=models.CharField(max_length=100),
        ),
    ]
