# Generated by Django 4.0.2 on 2022-04-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0005_ovcprevevaluation_date_of_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovcprevevaluation',
            name='form_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='OVCFMPEvaluation',
        ),
    ]
