# Generated by Django 4.0.2 on 2022-05-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0005_ovccarecaseexit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OVCCareCaseExit',
        ),
    ]
