# Generated by Django 4.0.2 on 2022-05-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_forms', '0005_remove_ovcbenchmarkmonitoring_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovcbenchmarkmonitoring',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='cpovc_registry.regperson'),
            preserve_default=False,
        ),
    ]
