# Generated by Django 4.0.2 on 2022-05-02 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '__first__'),
        ('cpovc_forms', '0006_delete_ovccarecaseexit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCCareCaseExit',
            fields=[
                ('case_clouse_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attrition_reason', models.CharField(max_length=10, null=True)),
                ('transfer_completed', models.CharField(max_length=10, null=True)),
                ('reason', models.CharField(max_length=10)),
                ('exit_reason_stored', models.CharField(max_length=10, null=True)),
                ('other', models.CharField(max_length=250, null=True)),
                ('case_files_completed', models.CharField(max_length=5, null=True)),
                ('cw_phone_household', models.CharField(max_length=5, null=True)),
                ('head_hh_linked', models.CharField(max_length=5, null=True)),
                ('sp_informed_graduation', models.CharField(max_length=5, null=True)),
                ('files_stored', models.CharField(max_length=5, null=True)),
                ('transfer_form_completed', models.CharField(max_length=5, null=True)),
                ('follow_up_frequency', models.CharField(max_length=5, null=True)),
                ('sp_informed_tarnsfer', models.CharField(max_length=5, null=True)),
                ('family_folder_sent', models.CharField(max_length=5, null=True)),
                ('attrition_documented', models.CharField(max_length=5, null=True)),
                ('manager_report', models.CharField(max_length=5, null=True)),
                ('receiving_org', models.CharField(max_length=250, null=True)),
                ('date_of_closure', models.DateField()),
                ('is_void', models.BooleanField(default=False)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(auto_now=True, null=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseclouse_caregiver', to='cpovc_registry.regperson')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseclouse_child', to='cpovc_registry.regperson')),
                ('rec_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit')),
            ],
            options={
                'db_table': 'ovc_closure_exit',
            },
        ),
    ]
