# Generated by Django 4.0.2 on 2022-05-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0006_ovcbenchmarkmonitoring_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovcbenchmarkmonitoring',
            name='person',
        ),
    ]
