# Generated by Django 4.0.2 on 2022-04-30 08:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_ovc', '0001_initial'),
        ('cpovc_forms', '0006_alter_ovchivmanagement_substitution_firstline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 11, 22, 49, 821497)),
        ),
        migrations.AlterField(
            model_name='ovcpreventiveevents',
            name='house_hold',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovchousehold'),
        ),
        migrations.AlterField(
            model_name='ovcprevsinovyoteenevaluation',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovcpreventiveevents'),
        ),
    ]
