# Generated by Django 4.0.2 on 2022-05-01 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_ovc', '0001_initial'),
        ('cpovc_forms', '0006_ovcprevevaluation_form_type_delete_ovcfmpevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCCareBidirectionPlan',
            fields=[
                ('bidirection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=50)),
                ('goal', models.CharField(max_length=255)),
                ('date_of_event', models.DateField()),
                ('date_of_previous_event', models.DateField(blank=True, null=True)),
                ('case_plan_status', models.CharField(max_length=5)),
                ('initial_caseplan', models.BooleanField(default=True)),
                ('is_void', models.BooleanField(default=False)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidirection_caregiver', to='cpovc_registry.regperson')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareforms')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovchousehold')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'db_table': 'ovc_bidirection',
            },
        ),
    ]
