# Generated by Django 4.0.4 on 2022-05-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '__first__'),
        ('cpovc_forms', '0006_ovcsubpopulation_delete_ovccarecpara'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovccarebenchmarkscore',
            name='care_giver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
    ]
