# Generated by Django 4.0.4 on 2022-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0007_remove_ovcbenchmarkmonitoring_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovcbenchmarkmonitoring',
            name='form_type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
