# Generated by Django 4.0.2 on 2022-05-05 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0007_alter_ovchivmanagement_substitution_firstline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 19, 19, 7, 600583)),
        ),
        migrations.AlterField(
            model_name='ovcprevsinovyocaregiverevaluation',
            name='date_of_assessment',
            field=models.DateTimeField(),
        ),
    ]
