# Generated by Django 4.0.4 on 2022-05-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0007_ovccarebenchmarkscore_care_giver_delete_ovccarecpara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovccarebenchmarkscore',
            name='household',
        ),
    ]
