# Generated by Django 4.0.2 on 2022-05-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0007_ovccarecaseexit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OVCCareCaseExit',
        ),
    ]
