# Generated by Django 4.0.2 on 2022-04-30 08:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0008_alter_ovchivmanagement_substitution_firstline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 11, 24, 49, 100295)),
        ),
        migrations.AlterField(
            model_name='ovcprevsinovyoteenevaluation',
            name='event',
            field=models.ForeignKey(default='e5a597d2-c85d-11ec-9457-8086f2150811', on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovcpreventiveevents'),
        ),
    ]
