# Generated by Django 4.0.4 on 2022-05-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0008_ovcbenchmarkmonitoring_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovcbenchmarkmonitoring',
            name='form_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
