# Generated by Django 4.0.4 on 2022-05-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0008_remove_ovccarebenchmarkscore_household_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OVCCareCpara',
        ),
    ]
