# Generated by Django 4.0.2 on 2022-05-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '__first__'),
        ('cpovc_forms', '0009_ovccarecaseexit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovccarecaseexit',
            name='receiving_org',
        ),
        migrations.RemoveField(
            model_name='ovccarecaseexit',
            name='transfer_completed',
        ),
        migrations.AddField(
            model_name='ovccarecaseexit',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regpersonsorgunits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ovccarecaseexit',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver', to='cpovc_registry.regperson'),
        ),
    ]
