# Generated by Django 4.0.2 on 2022-05-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0010_remove_ovccarecaseexit_receiving_org_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovccarecaseexit',
            name='other',
        ),
    ]
