# Generated by Django 4.0.4 on 2022-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0011_alter_ovcbireferral_client_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovcbireferral',
            name='refferal_date',
            field=models.DateField(),
        ),
    ]
