# Generated by Django 4.0.2 on 2022-05-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '__first__'),
        ('cpovc_forms', '0011_remove_ovccarecaseexit_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovccarecaseexit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
    ]
