# Generated by Django 4.0.4 on 2022-05-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_ovc', '__first__'),
        ('cpovc_forms', '0011_remove_ovccarebenchmarkscore_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovccarebenchmarkscore',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovchousehold'),
        ),
    ]
