# Generated by Django 4.0.4 on 2022-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0012_alter_ovcbireferral_refferal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovcbireferral',
            name='refferal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
