# Generated by Django 4.0.4 on 2022-05-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0014_ovccarebenchmarkscore_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovccarebenchmarkscore',
            name='care_giver',
        ),
    ]
