# Generated by Django 4.0.4 on 2022-05-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0016_ovccarebenchmarkscore_care_giver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ovcsubpopulation',
            old_name='person_id',
            new_name='person',
        ),
        migrations.AddField(
            model_name='ovcsubpopulation',
            name='event',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents'),
            preserve_default=False,
        ),
    ]
