# Generated by Django 4.0.4 on 2022-05-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0017_rename_person_id_ovcsubpopulation_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OVCSubPopulation',
        ),
    ]
