# Generated by Django 4.0.4 on 2022-05-03 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '__first__'),
        ('cpovc_forms', '0018_delete_ovcsubpopulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVCSubPopulation',
            fields=[
                ('sub_population_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria', models.CharField(max_length=10)),
                ('date_of_event', models.DateField()),
                ('is_void', models.BooleanField(default=False)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'db_table': 'ovc_sub_population',
            },
        ),
    ]
