# Generated by Django 4.0.2 on 2022-05-05 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0019_alter_ovchivmanagement_substitution_firstline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 23, 43, 30, 822141)),
        ),
        migrations.AlterField(
            model_name='ovcprevsinovyoteenevaluation',
            name='bd_bd_boarding_status',
            field=models.CharField(default='Not in School', max_length=10),
        ),
        migrations.AlterField(
            model_name='ovcprevsinovyoteenevaluation',
            name='bd_class',
            field=models.CharField(default='Not in School', max_length=100),
        ),
    ]
