# Generated by Django 4.0.4 on 2022-05-06 16:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '__first__'),
        ('cpovc_ovc', '__first__'),
        ('cpovc_forms', '0019_ovcsubpopulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovccarecpara_upgrade',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovc_cpara_caregiver', to='cpovc_registry.regperson'),
        ),
        migrations.CreateModel(
            name='OVCCareIndividaulCpara',
            fields=[
                ('cpara_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_code', models.CharField(blank=True, max_length=10)),
                ('answer', models.CharField(max_length=15)),
                ('question_type', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('date_of_event', models.DateField()),
                ('date_of_previous_event', models.DateField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpara_caregiver', to='cpovc_registry.regperson')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_ovc.ovchousehold')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpara_person', to='cpovc_registry.regperson')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccarequestions')),
            ],
            options={
                'db_table': 'ovc_care_Individual_cpara',
            },
        ),
    ]
