# Generated by Django 4.0.4 on 2022-05-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0020_alter_ovccarecpara_upgrade_caregiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OVCCareIndividaulCpara',
        ),
    ]
