# Generated by Django 4.0.2 on 2022-05-05 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0021_alter_ovchivmanagement_substitution_firstline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 0, 18, 20, 252636)),
        ),
        migrations.AlterField(
            model_name='ovcprevsinovyoteenevaluation',
            name='bd_bd_boarding_status',
            field=models.CharField(default='Not_in_School', max_length=10),
        ),
        migrations.AlterField(
            model_name='ovcprevsinovyoteenevaluation',
            name='bd_class',
            field=models.CharField(default='Not_in_School', max_length=100),
        ),
    ]
