# Generated by Django 4.0.4 on 2022-05-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0024_ovccareindividaulcpara'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OVCCareIndividaulCpara',
        ),
    ]
