# Generated by Django 4.0.4 on 2022-09-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0026_ovccareindividaulcpara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovccareevents',
            name='date_of_previous_event',
        ),
        migrations.AlterField(
            model_name='ovccaserecord',
            name='case_stage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
