from django.db import models


class Registrations(models.Model):
    cbo_id = models.IntegerField()
    cbo = models.CharField(max_length=255, null=True)
    ward_id = models.IntegerField()
    ward = models.CharField(max_length=100, null=True)
    consituency_id = models.IntegerField()
    constituency = models.CharField(max_length=100, null=True)
    countyid = models.IntegerField()
    county = models.CharField(max_length=100, null=True)
    cpims_ovc_id = models.IntegerField()
    ovc_names = models.TextField(null=True)
    gender = models.TextField(null=True)
    dob = models.DateField(null=True)
    date_of_birth  = models.DateField(null=True)
    age = models.FloatField(null=True)
    age_at_reg = models.FloatField(null=True)
    agerange = models.TextField(null=True)
    birthcert = models.TextField(null=True)
    bcertnumber = models.CharField(max_length=50, null=True)
    ovcdisability = models.TextField(null=True)
    ncpwdnumber = models.CharField(max_length=50, null=True)
    ovchivstatus = models.TextField(null=True)
    artstatus = models.TextField(null=True)
    facility_id = models.IntegerField()
    facility = models.CharField(max_length=200, null=True)
    facility_mfl_code = models.CharField(max_length=20, null=True)
    date_of_linkage = models.DateField(null=True)
    ccc_number = models.CharField(max_length=20, null=True)
    duration_on_art = models.TextField(null=True)
    viral_load = models.IntegerField()
    date_of_event = models.DateField(null=True)
    suppression = models.TextField(null=True)
    chv_id = models.IntegerField()
    chv_names = models.TextField(null=True)
    caregiver_id = models.IntegerField()
    caregiver_names = models.TextField(null=True)
    caregiver_dob = models.DateField(null=True)
    caregiver_age = models.FloatField(null=True)
    phone = models.IntegerField()
    caregiver_relation = models.CharField(max_length=255, null=True)
    caregiver_gender = models.TextField(null=True)
    caregiver_nationalid = models.CharField(max_length=255, null=True)
    caregiverhivstatus = models.TextField(null=True)
    household = models.UUIDField(null=True)
    caregiver_type = models.TextField(null=True)
    father_alive = models.TextField(null=True)
    mother_alive = models.TextField(null=True)
    schoollevel = models.TextField(null=True)
    school_id = models.IntegerField()
    school_name = models.CharField(max_length=200, null=True)
    school_class = models.CharField(max_length=10, null=True)
    registration_date = models.DateField(null=True)
    duration_in_program = models.TextField(null=True)
    immunization = models.TextField(null=True)
    eligibility = models.CharField(max_length=255, null=True)
    exit_status = models.TextField(null=True)
    exit_date = models.DateField(null=True)
    exit_reason = models.CharField(max_length=255, null=True)
    r_period = models.IntegerField()
    r_year = models.IntegerField()
	

    class Meta:
        managed = False
        db_table = 'ft_cpims_registration'