# Generated by Django 4.0.4 on 2022-10-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_registry', '0002_alter_ovchousehold_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.IntegerField(choices=[(1, 'USAID'), (2, 'CDC'), (3, 'DOD')], default=1)),
                ('targets', models.TextField(blank=True, max_length=250, null=True)),
                ('fyear', models.IntegerField(default=2022)),
                ('is_void', models.BooleanField(default=False)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lip', to='cpovc_registry.regorgunit')),
                ('parent_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip', to='cpovc_registry.regorgunit')),
            ],
            options={
                'verbose_name': 'IP Report',
                'verbose_name_plural': 'IP Reports',
                'db_table': 'report_ip',
            },
        ),
    ]
