# Generated by Django 4.0.4 on 2022-11-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0002_alter_ovchousehold_options'),
        ('cpovc_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COPTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.IntegerField(choices=[(1, 'USAID'), (2, 'CDC'), (3, 'DOD'), (4, 'PC'), (5, 'State/AF')], default=1)),
                ('agency', models.CharField(max_length=100)),
                ('mechanism', models.CharField(max_length=255)),
                ('county_id', models.IntegerField()),
                ('county', models.CharField(max_length=100)),
                ('hiv_burden', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('ovc_serv', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_under_1', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_1_9', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_10_14', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_15_17', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_18_24', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_coarse', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_uk', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_active', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_graduated', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_over_18', models.IntegerField(blank=True, default=0, null=True)),
                ('ovc_serv_under_18', models.IntegerField(blank=True, default=0, null=True)),
                ('tx_curr', models.IntegerField(blank=True, default=0, null=True)),
                ('tx_curr_under_1', models.IntegerField(blank=True, default=0, null=True)),
                ('tx_curr_1_9', models.IntegerField(blank=True, default=0, null=True)),
                ('tx_curr_10_14', models.IntegerField(blank=True, default=0, null=True)),
                ('tx_curr_15_19', models.IntegerField(blank=True, default=0, null=True)),
                ('fyear', models.IntegerField(default=2022)),
                ('is_void', models.BooleanField(default=False)),
                ('mech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit')),
            ],
            options={
                'verbose_name': 'COP Target',
                'verbose_name_plural': 'COP Targets',
                'db_table': 'report_cop_targets',
            },
        ),
    ]
