# Generated by Django 4.0.2 on 2022-03-04 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_auth', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cpovc_main', '0002_initial'),
        ('cpovc_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpovcuserrolegeoorg',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_main.setupgeography'),
        ),
        migrations.AddField(
            model_name='cpovcuserrolegeoorg',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_auth.cpovcrole'),
        ),
        migrations.AddField(
            model_name='cpovcuserrolegeoorg',
            name='org_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit'),
        ),
        migrations.AddField(
            model_name='cpovcuserrolegeoorg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='reg_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
