# Generated by Django 4.0.2 on 2022-03-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='reg_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
    ]
