# Generated by Django 4.0.4 on 2023-03-25 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_preventive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovcpreventiveebi',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_preventive.ovcpreventiveevents'),
        ),
        migrations.AlterField(
            model_name='ovcpreventiveregistration',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_preventive.ovcpreventivegroup'),
        ),
        migrations.AlterField(
            model_name='ovcpreventiveservice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_preventive.ovcpreventiveevents'),
        ),
    ]
