# Generated by Django 4.0.4 on 2023-03-25 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0002_alter_ovchousehold_options'),
        ('cpovc_preventive', '0002_alter_ovcpreventiveebi_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovcpreventiveservice',
            name='ebi_service_other',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ovcpreventiveservice',
            name='ebi_service_completed',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ovcpreventiveservice',
            name='ebi_service_reffered',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='OVCPreventiveEvaluation',
            fields=[
                ('evaluation_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.CharField(max_length=12)),
                ('question_answer', models.CharField(max_length=10)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('caregiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preval_caregiver', to='cpovc_registry.regperson')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_preventive.ovcpreventiveevents')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'db_table': 'ovc_preventive_evaluation',
            },
        ),
    ]
