"""Urls for reports."""
from django.urls import path, re_path
from django.conf.urls import patterns

# This should contain urls related to reports ONLY
urlpatterns = patterns(
    'cpovc_reports.views',
    path('', 'reports_home', name='reports'),
    path('documents/', 'reports_home',
        name='document_reports'),
    path('<int:id>/', 'reports_cpims',
        name='cpims_reports'),
    path('caseload/', 'reports_caseload',
        name='caseload_reports'),
    path('get_viral_load_report/', 'get_viral_load_report',
            name='get_viral_load_report'),
    path('manage/', 'manage_reports',
        name='manage_reports'),
    path('dashboard/', 'manage_dashboard',
        name='manage_dashboard'),
    re_path(r'^download/(?P<file_name>[0-9A-Za-z_\.=\-\' ]+)$',
        'reports_download', name='download_reports'),
    path('generate/', 'reports_generate',
        name='generate_reports'),
    path('pivot/', 'reports_pivot',
        name='pivot_reports'),
    path('data/', 'reports_rawdata',
        name='pivot_rawdata'),
    path('datim/', 'reports_ovc_pivot',
        name='pivot_ovc_reports'),
    path('datim_mer/', 'reports_ovc_datim_mer_pivot',
        name='pivot_ovc_reports_mer'),
    path('datim_mer23/', 'reports_ovc_datim_mer23_pivot',
        name='pivot_ovc_reports_mer23'),
    path('datim_mer24/', 'reports_ovc_datim_mer24_pivot',
        name='pivot_ovc_reports_mer24'),
    path('datim_mer25/', 'reports_ovc_datim_mer25_pivot', 
        name='pivot_ovc_reports_mer25'),
    path('pepfar/', 'reports_ovc_pepfar',
        name='pivot_ovc_pepfar'),
    path('kpi/', 'reports_ovc_kpi',
        name='pivot_ovc_kpi'),
    path('viral_load/', 'viral_load',
            name='viral_load'),
    path('ovcdata/', 'reports_ovc_rawdata',
        name='pivot_ovc_rawdata'),
    path('download/', 'reports_ovc_download',
        name='ovc_download'),
    path('ovc/<int:id>/', 'reports_ovc',
        name='reports_ovc'),
    path('dashboard/data/', 'dashboard_details',
        name='dashboard_details'),
    path('cluster/', 'cluster', name='cluster'),
    path('ovc/', 'reports_ovc_list', name='reports_ovc_list'),
     path('bursary/', 'reports_bursary', name='bursary_reports'),
    )


