"""paths for reports."""
from django.urls import path, re_path
from .views import (
    reports_home,reports_cpims, reports_caseload, get_viral_load_report,
    manage_reports,manage_dashboard,reports_generate,reports_pivot,reports_rawdata,
    reports_ovc_pivot,reports_ovc_datim_mer_pivot,reports_ovc_datim_mer23_pivot,
    reports_ovc_datim_mer24_pivot,reports_ovc_datim_mer25_pivot,reports_ovc_pepfar,
    reports_ovc_kpi,viral_load,reports_ovc_rawdata,reports_ovc_download,reports_ovc,
    dashboard_details,cluster,reports_ovc_list, reports_bursary
    
)
#changed from import patterns, urlto import include, path

# This should contain paths related to reports ONLY
urlpatterns = [
    path(r'^$', reports_home, name='reports'),
    path(r'^documents/$', reports_home,
        name='document_reports'),
    path(r'^<int:id>/$', reports_cpims,
        name='cpims_reports'),
    path(r'^caseload/$', reports_caseload,
        name='caseload_reports'),
    path(r'^get_viral_load_report/$', get_viral_load_report,
            name='get_viral_load_report'),
    path(r'^manage/$', manage_reports,
        name='manage_reports'),
    path(r'^dashboard/$', manage_dashboard,
        name='manage_dashboard'),
    re_path(r'^download/(?P<uidb64>[0-9A-Za-z_\.=\-\' ]+)$',
        'reports_download', name='download_reports'),
    path(r'^generate/$', reports_generate,
        name='generate_reports'),
    path(r'^pivot/$', reports_pivot,
        name='pivot_reports'),
    path(r'^data/$', reports_rawdata,
        name='pivot_rawdata'),
    path(r'^datim/$', reports_ovc_pivot,
        name='pivot_ovc_reports'),
    path(r'^datim_mer/$', reports_ovc_datim_mer_pivot,
        name='pivot_ovc_reports_mer'),
    path(r'^datim_mer23/$', reports_ovc_datim_mer23_pivot,
        name='pivot_ovc_reports_mer23'),
    path(r'^datim_mer24/$', reports_ovc_datim_mer24_pivot,
        name='pivot_ovc_reports_mer24'),
    path(r'^datim_mer25/$', reports_ovc_datim_mer25_pivot, 
        name='pivot_ovc_reports_mer25'),
    path(r'^pepfar/$', reports_ovc_pepfar,
        name='pivot_ovc_pepfar'),
    path(r'^kpi/$', reports_ovc_kpi,
        name='pivot_ovc_kpi'),
    path(r'^viral_load/$', viral_load,
            name='viral_load'),
    path(r'^ovcdata/$', reports_ovc_rawdata,
        name='pivot_ovc_rawdata'),
    path(r'^download/$', reports_ovc_download,
        name='ovc_download'),
    path(r'^ovc/(?P<id>\d+)/$', reports_ovc,
        name='reports_ovc'),
    path(r'^dashboard/data/$', dashboard_details,
        name='dashboard_details'),
    path(r'^cluster/$', cluster,
         name='cluster'),
    path(r'^ovc/$', reports_ovc_list,
         name='reports_ovc_list'),
    path(r'^bursary/$', reports_bursary, 
        name='bursary_reports'),
]