# Generated by Django 4.0.4 on 2022-05-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_ovc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ovchhmembers',
            options={'verbose_name': 'OVC HH Member', 'verbose_name_plural': 'OVC HH Members'},
        ),
        migrations.AlterModelOptions(
            name='ovchousehold',
            options={'verbose_name': 'OVC Household', 'verbose_name_plural': 'OVC Households'},
        ),
    ]
